<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-28161K9" failures="1" tests="3" name="AddToCart" time="36.047" errors="0" timestamp="2022-12-13T22:48:05 IST">
  <testcase classname="shop.Tests.LaunchShopTest" name="openBrowser" time="21.414"/>
  <testcase classname="shop.Tests.AddToCartTest" name="addToCart" time="11.349">
    <skipped/>
  </testcase> <!-- addToCart -->
  <testcase classname="shop.Tests.AddToCartTest" name="addToCart" time="1.155">
    <failure type="java.lang.AssertionError" message="expected [Success! 11Item is successfully added to cart..] but found [Success! Item is successfully added to cart..]">
      <![CDATA[java.lang.AssertionError: expected [Success! 11Item is successfully added to cart..] but found [Success! Item is successfully added to cart..]
at shop.Tests.AddToCartTest.addToCart(AddToCartTest.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- addToCart -->
</testsuite> <!-- AddToCart -->
