<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-28161K9" failures="1" tests="2" name="AddToCart" time="21.164" errors="0" timestamp="2022-12-12T23:34:47 IST">
  <testcase classname="shop.Tests.LaunchShopTest" name="openBrowser" time="14.156"/>
  <testcase classname="shop.Tests.AddToCartTest" name="addToCart" time="6.06">
    <failure type="java.lang.AssertionError" message="expected [Success! 1Item is successfully added to cart..] but found [Success! Item is successfully added to cart..]">
      <![CDATA[java.lang.AssertionError: expected [Success! 1Item is successfully added to cart..] but found [Success! Item is successfully added to cart..]
at shop.Tests.AddToCartTest.addToCart(AddToCartTest.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- addToCart -->
</testsuite> <!-- AddToCart -->
